trigger:
  - main
pool: 
 name: 'ubuntu-latest'

stages:
  - stage: build
    displayName: login to acr
    jobs:
      - job: build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'acr-connection'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'