trigger:
  - main
pool: 
 vmImage: 'ubuntu-latest'

stages:
  - stage: build
    displayName: login to acr
    jobs:
      - job: build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'acr-connection'
              repository: 'pythonimg'
              command: 'build'
              Dockerfile: 'Docker/docker-file/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
          - task: Docker@2
            inputs:
              containerRegistry: 'acr-connection'
              repository: 'pythonimg'
              command: 'push'
           